### ISSUE TITLE
Images are massive and should not be.

### ISSUE THREAD

**Issue by TFoley1** [TFoley1/theRowe#7]
Despite all my efforts all my images are bigger than they should be. While editing the code on [glitch.com](https://glitch.com) the images are fine. When they are hosted on github its completely different. [glitch version](https://the-rowe.glitch.me/index.html) and [github version](https://tfoley1.github.io/theRowe/) for comparison.

**Comment by Aryan-Bhatt-pro** [comment]
Hi, can I work on it?

**Comment by TFoley1** [comment]
Of course, I haven't figured it out yet so why not?

**Comment by TFoley1** [comment]
Solved the issue, was quite a small one. Images are now normal and ccs is normal.
